// this interface is for the IP address blocks
export interface IIPAddressBlock {
    town: string;
    segment1: number;
    segment2: number;
    segment3low: number;
    segment3high: number;
}

// here's a list of towns in Texas to check against
export const townsInTexas = [
    `Abbott`,
    `Abernathy`,
    `Abilene`,
    `Ackerly`,
    `Addison`,
    `Agua Dulce`,
    `Alamo`,
    `Alba`,
    `Albany`,
    `Aledo`,
    `Alice`,
    `Allen`,
    `Alpine`,
    `Alto`,
    `Alvarado`,
    `Alvin`,
    `Alvord`,
    `Amarillo`,
    `Amherst`,
    `Anahuac`,
    `Anderson`,
    `Andrews`,
    `Angleton`,
    `Anna`,
    `Annona`,
    `Anson`,
    `Anthony`,
    `Anton`,
    `Aransas Pass`,
    `Archer City`,
    `Argyle`,
    `Arlington`,
    `Arp`,
    `Asherton`,
    `Aspermont`,
    `Athens`,
    `Atlanta`,
    `Aubrey`,
    `Austin`,
    `Avery`,
    `Avinger`,
    `Azle`,
    `Bacliff`,
    `Bailey`,
    `Baird`,
    `Ballinger`,
    `Balmorhea`,
    `Bandera`,
    `Bangs`,
    `Bardwell`,
    `Barry`,
    `Barstow`,
    `Bartlett`,
    `Bastrop`,
    `Batesville`,
    `Bay City`,
    `Bayside`,
    `Baytown`,
    `Beasley`,
    `Beaumont`,
    `Beckville`,
    `Bedford`,
    `Beeville`,
    `Bellaire`,
    `Bellevue`,
    `Bells`,
    `Bellville`,
    `Belton`,
    `Benavides`,
    `Benjamin`,
    `Bertram`,
    `Big Lake`,
    `Big Sandy`,
    `Big Spring`,
    `Big Wells`,
    `Bigfoot`,
    `Bishop`,
    `Blackwell`,
    `Blanco`,
    `Blanket`,
    `Blessing`,
    `Bloomburg`,
    `Blooming Grove`,
    `Bloomington`,
    `Blossom`,
    `Blue Ridge`,
    `Blum`,
    `Boerne`,
    `Bogata`,
    `Boling`,
    `Bonham`,
    `Booker`,
    `Borger`,
    `Bovina`,
    `Bowie`,
    `Boyd`,
    `Brackettville`,
    `Brady`,
    `Brazoria`,
    `Breckenridge`,
    `Bremond`,
    `Brenham`,
    `Bridge City`,
    `Bridgeport`,
    `Bronte`,
    `Brookshire`,
    `Brownfield`,
    `Brownsboro`,
    `Brownsville`,
    `Brownwood`,
    `Bruceville`,
    `Bruni`,
    `Bryan`,
    `Bryson`,
    `Buchanan Dam`,
    `Buckholts`,
    `Buda`,
    `Buffalo Gap`,
    `Buffalo`,
    `Bullard`,
    `Bulverde`,
    `Buna`,
    `Burkburnett`,
    `Burkeville`,
    `Burleson`,
    `Burnet`,
    `Burton`,
    `Byers`,
    `Bynum`,
    `Daingerfield`,
    `Daisetta`,
    `Dalhart`,
    `Dallas`,
    `Damon`,
    `Danbury`,
    `Darrouzett`,
    `Dawson`,
    `Dayton`,
    `De Kalb`,
    `De Leon`,
    `Deanville`,
    `Decatur`,
    `Deer Park`,
    `Del Rio`,
    `Dell City`,
    `Denison`,
    `Denton`,
    `Denver City`,
    `Deport`,
    `Desoto`,
    `Detroit`,
    `Devers`,
    `Devine`,
    `Deweyville`,
    `Diboll`,
    `Dickens`,
    `Dickinson`,
    `Dilley`,
    `Dimmitt`,
    `Dodd City`,
    `Donna`,
    `Driscoll`,
    `Dublin`,
    `Dumas`,
    `Duncanville`,
    `Eagle Lake`,
    `Eagle Pass`,
    `Early`,
    `Earth`,
    `East Bernard`,
    `Eastland`,
    `Easton`,
    `Ector`,
    `Edcouch`,
    `Eden`,
    `Edgewood`,
    `Edinburg`,
    `Edna`,
    `Edroy`,
    `El Campo`,
    `El Indio`,
    `El Paso`,
    `Eldorado`,
    `Electra`,
    `Elgin`,
    `Elkhart`,
    `Elmendorf`,
    `Elsa`,
    `Emory`,
    `Encinal`,
    `Ennis`,
    `Euless`,
    `Eustace`,
    `Evadale`,
    `Evant`,
    `Fabens`,
    `Fairfield`,
    `Falcon Heights`,
    `Falfurrias`,
    `Falls City`,
    `Farmersville`,
    `Farwell`,
    `Fate`,
    `Fayetteville`,
    `Ferris`,
    `Flatonia`,
    `Florence`,
    `Floresville`,
    `Flower Mound`,
    `Floydada`,
    `Forney`,
    `Forsan`,
    `Fort Davis`,
    `Fort Hancock`,
    `Fort Stockton`,
    `Fort Worth`,
    `Franklin`,
    `Frankston`,
    `Fredericksburg`,
    `Freeport`,
    `Freer`,
    `Fresno`,
    `Friendswood`,
    `Friona`,
    `Frisco`,
    `Fritch`,
    `Frost`,
    `Fruitvale`,
    `Fulshear`,
    `Fulton`,
    `Gainesville`,
    `Galena Park`,
    `Gallatin`,
    `Galveston`,
    `Ganado`,
    `Gardendale`,
    `Garland`,
    `Garrison`,
    `Gary`,
    `Gatesville`,
    `George West`,
    `Georgetown`,
    `Geronimo`,
    `Giddings`,
    `Gilmer`,
    `Gladewater`,
    `Glen Rose`,
    `Godley`,
    `Goldsmith`,
    `Goldthwaite`,
    `Goliad`,
    `Gonzales`,
    `Goodrich`,
    `Gordon`,
    `Goree`,
    `Gorman`,
    `Graford`,
    `Graham`,
    `Granbury`,
    `Grand Prairie`,
    `Grand Saline`,
    `Grandfalls`,
    `Grandview`,
    `Granger`,
    `Grapeland`,
    `Grapevine`,
    `Greenville`,
    `Gregory`,
    `Groesbeck`,
    `Groom`,
    `Groves`,
    `Groveton`,
    `Gruver`,
    `Gunter`,
    `Gustine`,
    `Hale Center`,
    `Hallettsville`,
    `Hallsville`,
    `Hamilton`,
    `Hamlin`,
    `Happy`,
    `Hardin`,
    `Harker Heights`,
    `Harlingen`,
    `Harper`,
    `Hart`,
    `Hartley`,
    `Haskell`,
    `Haslet`,
    `Hawkins`,
    `Hawley`,
    `Hearne`,
    `Hebbronville`,
    `Hedley`,
    `Helotes`,
    `Hemphill`,
    `Hempstead`,
    `Henderson`,
    `Henrietta`,
    `Hereford`,
    `Hermleigh`,
    `Hewitt`,
    `Hico`,
    `Hidalgo`,
    `Higgins`,
    `Highlands`,
    `Hillsboro`,
    `Hitchcock`,
    `Holland`,
    `Holliday`,
    `Hondo`,
    `Honey Grove`,
    `Hooks`,
    `Houston`,
    `Howe`,
    `Hubbard`,
    `Hughes Springs`,
    `Humble`,
    `Hungerford`,
    `Huntington`,
    `Huntsville`,
    `Hurst`,
    `Hutchins`,
    `Idalou`,
    `Imperial`,
    `Industry`,
    `Inez`,
    `Ingleside`,
    `Ingram`,
    `Iowa Park`,
    `Iraan`,
    `Iredell`,
    `Irving`,
    `Italy`,
    `Itasca`,
    `Jacksboro`,
    `Jacksonville`,
    `Jasper`,
    `Jayton`,
    `Jefferson`,
    `Jewett`,
    `Joaquin`,
    `Johnson City`,
    `Josephine`,
    `Joshua`,
    `Karnes City`,
    `Kaufman`,
    `Keene`,
    `Kemah`,
    `Kemp`,
    `Kempner`,
    `Kendleton`,
    `Kenedy`,
    `Kennard`,
    `Kennedale`,
    `Kerens`,
    `Kermit`,
    `Kerrville`,
    `Kilgore`,
    `Killeen`,
    `Kingsbury`,
    `Kingsland`,
    `Kingsville`,
    `Kirbyville`,
    `Knippa`,
    `Knox City`,
    `Kosse`,
    `Kountze`,
    `Kress`,
    `Krum`,
    `Kyle`,
    `La Blanca`,
    `La Coste`,
    `La Feria`,
    `La Grange`,
    `La Joya`,
    `La Marque`,
    `La Porte`,
    `La Pryor`,
    `La Vernia`,
    `La Villa`,
    `Ladonia`,
    `Lake Dallas`,
    `Lake Jackson`,
    `Lamesa`,
    `Lampasas`,
    `Lancaster`,
    `Laredo`,
    `Lasara`,
    `Latexo`,
    `Laughlin A F B`,
    `Lavon`,
    `Lawn`,
    `League City`,
    `Leakey`,
    `Leander`,
    `Lefors`,
    `Leonard`,
    `Leroy`,
    `Levelland`,
    `Lewisville`,
    `Lexington`,
    `Liberty Hill`,
    `Liberty`,
    `Lincoln`,
    `Lindale`,
    `Linden`,
    `Lindsay`,
    `Lipann`,
    `Little Elm`,
    `Little River Academy`,
    `Littlefield`,
    `Liverpool`,
    `Livingston`,
    `Llano`,
    `Lockhart`,
    `Lockney`,
    `Lolita`,
    `Lometa`,
    `Lone Oak`,
    `Lone Star`,
    `Longview`,
    `Loraine`,
    `Lorena`,
    `Los Ebanos`,
    `Los Fresnos`,
    `Los Indios`,
    `Lott`,
    `Lozano`,
    `Lubbock`,
    `Lueders`,
    `Lufkin`,
    `Lumberton`,
    `Lyford`,
    `Lytle`,
    `Mabank`,
    `Madisonville`,
    `Magnolia`,
    `Malakoff`,
    `Malone`,
    `Manor`,
    `Mansfield`,
    `Manvel`,
    `Marble Falls`,
    `Marfa`,
    `Marion`,
    `Markham`,
    `Marlin`,
    `Marquez`,
    `Marshall`,
    `Mart`,
    `Martindale`,
    `Mason`,
    `Matador`,
    `Mathis`,
    `Maud`,
    `Mauriceville`,
    `Maypearl`,
    `Mc Camey`,
    `Mc Gregor`,
    `Mc Kinney`,
    `Mc Queeney`,
    `Mcallen`,
    `Mclean`,
    `Meadow`,
    `Medina`,
    `Megargel`,
    `Melissa`,
    `Memphis`,
    `Menard`,
    `Mercedes`,
    `Meridian`,
    `Merkel`,
    `Mertzon`,
    `Mesquite`,
    `Mexia`,
    `Miami`,
    `Midland`,
    `Midlothian`,
    `Midway`,
    `Milam`,
    `Milano`,
    `Miles`,
    `Milford`,
    `Millsap`,
    `Mineola`,
    `Mineral Wells`,
    `Mingus`,
    `Mirando City`,
    `Mission`,
    `Missouri City`,
    `Monahans`,
    `Mont Belvieu`,
    `Montgomery`,
    `Moody`,
    `Moore`,
    `Moran`,
    `Morgan`,
    `Morton`,
    `Moulton`,
    `Mount Calm`,
    `Mount Enterprise`,
    `Mount Pleasant`,
    `Mount Vernon`,
    `Muenster`,
    `Muleshoe`,
    `Munday`,
    `Murchison`,
    `Nacogdoches`,
    `Naples`,
    `Nash`,
    `Natalia`,
    `Navasota`,
    `Nazareth`,
    `Nederland`,
    `Needville`,
    `Nevada`,
    `New Boston`,
    `New Braunfels`,
    `New Deal`,
    `New Home`,
    `New London`,
    `New Summerfield`,
    `New Waverly`,
    `Newark`,
    `Newcastle`,
    `Newton`,
    `Nixon`,
    `Nocona`,
    `Nolanville`,
    `Nome`,
    `Nordheim`,
    `Normangee`,
    `North Richland Hills`,
    `Oakhurst`,
    `Oakwood`,
    `Odem`,
    `Odessa`,
    `Oglesby`,
    `Oilton`,
    `Olmito`,
    `Olney`,
    `Olton`,
    `Omaha`,
    `Onalaska`,
    `Orange Grove`,
    `Orange`,
    `Orchard`,
    `Ore City`,
    `Overton`,
    `Ozona`,
    `Paducah`,
    `Paint Rock`,
    `Palacios`,
    `Palestine`,
    `Palmer`,
    `Pampa`,
    `Panhandle`,
    `Paradise`,
    `Paris`,
    `Pasadena`,
    `Pattison`,
    `Pawnee`,
    `Pearland`,
    `Pearsall`,
    `Pecan Gap`,
    `Pecos`,
    `Penelope`,
    `Penitas`,
    `Perryton`,
    `Petersburg`,
    `Petrolia`,
    `Pettus`,
    `Pflugerville`,
    `Pharr`,
    `Pilot Point`,
    `Pinehurst`,
    `Pineland`,
    `Pittsburg`,
    `Plains`,
    `Plainview`,
    `Plano`,
    `Pleasanton`,
    `Plum`,
    `Point Comfort`,
    `Point`,
    `Ponder`,
    `Port Aransas`,
    `Port Arthur`,
    `Port Isabel`,
    `Port Lavaca`,
    `Port Mansfield`,
    `Port Neches`,
    `Porter`,
    `Portland`,
    `Post`,
    `Poteet`,
    `Poth`,
    `Pottsboro`,
    `Poynor`,
    `Prairie View`,
    `Premont`,
    `Presidio`,
    `Princeton`,
    `Progreso`,
    `Quanah`,
    `Queen City`,
    `Quemado`,
    `Quinlan`,
    `Quitaque`,
    `Quitman`,
    `Ralls`,
    `Ranger`,
    `Rankin`,
    `Ransom Canyon`,
    `Ravenna`,
    `Raymondville`,
    `Realitos`,
    `Red Oak`,
    `Redwater`,
    `Refugio`,
    `Reklaw`,
    `Rhome`,
    `Rice`,
    `Richardson`,
    `Richland Springs`,
    `Richland`,
    `Richmond`,
    `Riesel`,
    `Rio Grande City`,
    `Rio Hondo`,
    `Rio Vista`,
    `Rising Star`,
    `Roanoke`,
    `Roaring Springs`,
    `Robert Lee`,
    `Robstown`,
    `Roby`,
    `Rochester`,
    `Rockdale`,
    `Rockport`,
    `Rocksprings`,
    `Rockwall`,
    `Rogers`,
    `Roma`,
    `Ropesville`,
    `Roscoe`,
    `Rosebud`,
    `Rosenberg`,
    `Ross`,
    `Rosser`,
    `Rotan`,
    `Round Rock`,
    `Rowlett`,
    `Roxton`,
    `Royse City`,
    `Rule`,
    `Runge`,
    `Rusk`,
    `Sabinal`,
    `Sachse`,
    `Sadler`,
    `Saint Hedwig`,
    `Saint Jo`,
    `Salado`,
    `Salineno`,
    `San Angelo`,
    `San Antonio`,
    `San Augustine`,
    `San Benito`,
    `San Diego`,
    `San Elizario`,
    `San Felipe`,
    `San Isidro`,
    `San Juan`,
    `San Marcos`,
    `San Perlita`,
    `San Saba`,
    `Sanderson`,
    `Sandia`,
    `Sanford`,
    `Sanger`,
    `Santa Anna`,
    `Santa Fe`,
    `Santa Maria`,
    `Santa Rosa`,
    `Savoy`,
    `Schertz`,
    `Schulenburg`,
    `Scotland`,
    `Scottsville`,
    `Seabrook`,
    `Seadrift`,
    `Seagoville`,
    `Seagraves`,
    `Sealy`,
    `Sebastian`,
    `Seguin`,
    `Seminole`,
    `Seymour`,
    `Shallowater`,
    `Shamrock`,
    `Shepherd`,
    `Sherman`,
    `Shiner`,
    `Sierra Blanca`,
    `Silsbee`,
    `Silverton`,
    `Simonton`,
    `Sinton`,
    `Skellytown`,
    `Skidmore`,
    `Slaton`,
    `Smiley`,
    `Smithville`,
    `Smyer`,
    `Snook`,
    `Snyder`,
    `Somerset`,
    `Somerville`,
    `Sonora`,
    `Sour Lake`,
    `South Houston`,
    `South Padre Island`,
    `Southlake`,
    `Southmayd`,
    `Spearman`,
    `Splendora`,
    `Spring`,
    `Springtown`,
    `Spur`,
    `Stafford`,
    `Stamford`,
    `Stanton`,
    `Star`,
    `Stephenville`,
    `Sterling City`,
    `Stinnett`,
    `Stockdale`,
    `Stonewall`,
    `Stowell`,
    `Stratford`,
    `Strawn`,
    `Streetman`,
    `Sudan`,
    `Sugar Land`,
    `Sullivan City`,
    `Sulphur Springs`,
    `Sundown`,
    `Sunnyvale`,
    `Sunray`,
    `Sunset`,
    `Sweeny`,
    `Sweetwater`,
    `Taft`,
    `Tahoka`,
    `Talco`,
    `Tatum`,
    `Taylor`,
    `Teague`,
    `Tehuacana`,
    `Temple`,
    `Tenaha`,
    `Terrell`,
    `Texarkana`,
    `Texas City`,
    `Texline`,
    `The Colony`,
    `Thompsons`,
    `Thorndale`,
    `Thornton`,
    `Thrall`,
    `Three Rivers`,
    `Throckmorton`,
    `Timpson`,
    `Tioga`,
    `Tolar`,
    `Tom Bean`,
    `Tomball`,
    `Tornillo`,
    `Trent`,
    `Trenton`,
    `Trinidad`,
    `Trinity`,
    `Troup`,
    `Troy`,
    `Tuleta`,
    `Tulia`,
    `Turkey`,
    `Tuscola`,
    `Tye`,
    `Tyler`,
    `Tynan`,
    `Universal City`,
    `Utopia`,
    `Uvalde`,
    `Valley Mills`,
    `Valley View`,
    `Van Alstyne`,
    `Van Horn`,
    `Van Vleck`,
    `Van`,
    `Vanderbilt`,
    `Vega`,
    `Venus`,
    `Vernon`,
    `Victoria`,
    `Vidor`,
    `Waco`,
    `Waelder`,
    `Waller`,
    `Wallis`,
    `Walnut Springs`,
    `Warren`,
    `Waskom`,
    `Waxahachie`,
    `Weatherford`,
    `Webster`,
    `Weimar`,
    `Weir`,
    `Wellington`,
    `Wellman`,
    `Wells`,
    `Weslaco`,
    `West Columbia`,
    `West`,
    `Westbrook`,
    `Westminster`,
    `Weston`,
    `Wharton`,
    `Wheeler`,
    `White Deer`,
    `White Oak`,
    `Whiteface`,
    `Whitehouse`,
    `Whitesboro`,
    `Whitewright`,
    `Whitney`,
    `Wichita Falls`,
    `Wickett`,
    `Willis`,
    `Wills Point`,
    `Wilmer`,
    `Wilson`,
    `Wimberley`,
    `Windom`,
    `Windthorst`,
    `Winfield`,
    `Wink`,
    `Winnie`,
    `Winona`,
    `Winters`,
    `Wolfe City`,
    `Wolfforth`,
    `Woodsboro`,
    `Woodson`,
    `Woodville`,
    `Woodway`,
    `Wortham`,
    `Wylie`,
    `Yantis`,
    `Yoakum`,
    `Yorktown`,
    `Zapata`,
    `Zavalla`
]
    
// these functions validate the IP address blocks

const validateSegmentValue = (value: number): boolean => {
    if ( 255 > value && value >= 0 ) {
        return true;
    }
    else {
        return false;
    }
}

const validateTown = (value: string): boolean => {
    if ( townsInTexas.includes(value) ) {
        return true;
    }
    else {
        return false;
    }
}

export const validateIPAddressBlock = (block: IIPAddressBlock): boolean => {
    if (validateTown(block.town) &&
        validateSegmentValue(block.segment1) &&
        validateSegmentValue(block.segment2) &&
        validateSegmentValue(block.segment3low) && validateSegmentValue(block.segment3high) &&
        (block.segment3low <= block.segment3high)) {
        return true
    }
    else return false
}